### ISSUE TITLE
set 'no group' for local packages 

### ISSUE THREAD

**Issue by MartinP7r** [yonaskolb/XcodeGen#1209]
Is there a way to set no group for a local package?  
At the moment there's the `group` option for local packages and [`localPackagesGroup`](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#local-package), but neither can be set to something that allows a package to sit at the projects root without a group.

**Comment by MartinP7r** [comment]
I believe this has similarity to https://github.com/yonaskolb/XcodeGen/issues/1118

**Comment by hiltonc** [comment]
I would like this behavior as well. Currently the best I can do is put the local packages in a top-level folder, like:

```
/MyProject
  /Packages
    /Package1
    /Package2
```

What I want is:

```
/MyProject
  /Package1
  /Package2
```

Looking at https://github.com/yonaskolb/XcodeGen/blob/26fc38a664cae9e2a76ec23566820a1dcfe4099c/Sources/XcodeGenKit/SourceGenerator.swift#L56-L88 I don't see a way to configure the package's `group` and `localPackagesGroup` that doesn't put it in at least one folder.

**Comment by yonaskolb** [comment]
@hiltonc I'm happy with that solution (setting group to "") or allowing `options.localPackagesGroup` to be "", if you'd like to make a PR

**Comment by hiltonc** [comment]
@yonaskolb Thanks, I added support for both options in #1413.

**Comment by MartinP7r** [comment]
Thank you @hiltonc!

**Comment by MartinP7r** [comment]
Now we only need someone to review. 🥺

**Comment by MartinP7r** [comment]
@yonaskolb would you be able to review or assign/recommend someone able to review?

**Comment by vahan3x** [comment]
The resolution here (options.localPackagesGroup: "") only relocates the local-package folder reference to the project root - it can't remove it. Local packages still get a dual representation: the XCLocalSwiftPackageReference under Package Dependencies plus a browsable folder PBXFileReference in the navigator. When you add a local package through Xcode's own "Add Package Dependencies… > Add Local", only the Package Dependencies entry is created without a duplicate group inside the main project.

I'd like to propose a new global option to match that behaviour:

options:
  createLocalPackageGroups: false  # default: true
When false, XcodeGen still emits the XCLocalSwiftPackageReference (Package Dependencies stays populated) but skips creating the folder reference/group for all local packages. Default true keeps current output byte-for-byte, so it's fully backward compatible and a minimal diff - the folder is only created in one place (SourceGenerator.createLocalPackage), so it's a single gated call.

I have a working implementation with tests and docs ready to submit as a PR. @yonaskolb would you take this, or would you prefer a different name/shape (e.g. a per-package group: none-style key instead of a global option)?

<details>
<summary>Screenshots</summary>

| Current | My change |
| - | - |
| <img width="290" height="401" alt="Image" src="https://github.com/user-attachments/assets/57e016ae-1116-43b0-9b7e-c9d2876d1e7a" /> | <img width="290" height="401" alt="Image" src="https://github.com/user-attachments/assets/27283b58-0cc4-4b28-ab69-6331a900c29f" /> |

</details>
