### ISSUE TITLE
Serialize `ProjectSpec` to JSON

### ISSUE THREAD

**Issue by jerrymarino** [yonaskolb/XcodeGen#123]
Good afternoon!

Thanks so much for creating XcodeGen, the project is great.

I'd like to use the `ProjectSpec` and children as a protocol to write out a JSON file. My custom generator would be allocating data structures in `ProjectSpec` directly

Without being able to write the `ProjectSpec` and dependencies to JSON, I need to implement my own version of the spec ( currently on Swift 4 codeable ).

Is this something Xcode gen would support?

**Comment by yonaskolb** [comment]
Thanks @jerrymarino!
Getting the ProjectSpec to support Codable is possible, but slightly tricky due to the quite dynamic nature of the scheme. Codable in it's default state is quite strict in how things should be represented. It's something I want to add though. Feel free to open a PR for it 👍 

Could you explain your usecase a bit more? You would be creating the ProjectSpec in Swift and then generating JSON form that to be used in your own project generator?

**Comment by jerrymarino** [comment]
@yonaskolb awesome! I was looking at Spec JSON coding implementation this morning, and can see that this would be quite an undertaking. I think it is a better direction than writing and maintaining my own ( dumbed down ) version of it. In a way, this spec is the public API of XcodeGen, so having the data structures writing to a JSON file, would be super useful.

I'm taking iOS build configurations and writing an Xcode project that builds an iOS per that configuration. The program uses XcodeGen to achieve part of the process - XcodeGen reads in a JSON rep of the spec.
