### ISSUE TITLE
run xcodegen in jenkins script

### ISSUE THREAD

**Issue by WHuangz88** [yonaskolb/XcodeGen#1289]
Hi guys, so recently i want to configure jenkins, but having hard time to find how to run xcodegen from my jenkinsfile

need help

**Comment by technocidal** [comment]
@WHuangz88

Jenkinsfile include the option to run arbitrary programs using the [`sh`](https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/) command inside your declarative pipeline.

This means, that you can run Xcodegen like this 
```
pipeline {
    agent any

    stages {
        stage('Xcodegen') {
            steps {
                sh 'xcodegen'
            }
        }
    }
}
```

Obviously this requires Xcodegen to be installed on your CI machine. You can achieve this using a whole bunch of ways but maybe as a start you can probably just take the installation steps in the [Xcodegen README](https://github.com/yonaskolb/XcodeGen/blob/master/README.md) and add them to your Jenkinsfile as well so that the pipeline makes sure, that `Xcodegen` is installed before trying to run it.
