### ISSUE TITLE
Generates Project with Extra Schemes (SPM Dependencies)

### ISSUE THREAD

**Issue by OmranK** [yonaskolb/XcodeGen#1356]
Not sure why (sometimes they are there, sometimes not) but xcodegen command creates a project with extra schemes that correlate to some of my Swift package dependencies. See lines 1 & 3:

![Screenshot 2023-05-08 at 6 34 09 PM](https://user-images.githubusercontent.com/33832722/236952387-13f96a61-84aa-4b91-b43a-e27452bd1bce.png)

**Comment by yonaskolb** [comment]
This is Xcode deciding you would like those schemes 🤷‍♂️  
You can disable it in the scheme management window. 

<img width="763" alt="Screenshot 2023-05-09 at 6 39 35 pm" src="https://user-images.githubusercontent.com/2393781/237042381-18797968-5ab0-4b12-90c4-fc62b717db17.png">

This writes a file to `Project.xcodeproj/project.xcworkspace/xcshareddata/WorkSpaceSettings.xcsettings`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded</key>
	<false/>
</dict>
</plist>
```
You can check this file into git without checking other parts of the project in, or write it in a post gen script. Last I remember [XcodeProj](https://github.com/tuist/XcodeProj) didn't have support for writing that file, and I'm not sure if that has changed since
