### ISSUE TITLE
Swift compile error: Switch must be exhaustive

### ISSUE THREAD

**Issue by bagipro** [yonaskolb/XcodeGen#1381]
Swift doesn't build the library because of an error in this `switch`:
https://github.com/yonaskolb/XcodeGen/blob/master/Sources/ProjectSpec/Breakpoint.swift#L217

It suggests also adding
```swift
        case .runtimeIssue:
            <#code#>
        }
```

The issue is reproducible when I'm following the instruction and using the latest available version

**Comment by yonaskolb** [comment]
This is due to a breaking XcodeProj update. It is pinned to an earlier version in this repo in Package.resolved, but when a package is used as a dependency it's up to the parent package to determine maximum versions.

XcodeProj has been updated here to fix this issue https://github.com/yonaskolb/XcodeGen/pull/1384
