### ISSUE TITLE
Framework public headers folder structure

### ISSUE THREAD

**Issue by libe** [yonaskolb/XcodeGen#242]
Hello,

first of all thanks for this great tool, digging it a lot so far! 

I need to have a defined folder structure in the Public Headers section of my framework but so far I am struggling to obtain this through XcodeGen.

Basically if I declare a folder like:
      - path: MyProject/ProtectedInterfaces/Foo
        buildPhase: headers
        type: folder

I would expect to have the folder Foo copied in the Headers folder of my framework. But what I get actually copied is each single files contained in Foo so and the structure is not respected (and my client cannot properly include the framework).

Do you have any idea on how I can accomplish this?

Thanks!

**Comment by yonaskolb** [comment]
Hi @libe 
Glad you're digging it.

I'll assume that the yaml snippet you posted has correct indentation in your actual spec, so that the `buildPhase` and `type` properties are properly matched to your path declaration?
```
- path: MyProject/ProtectedInterfaces/Foo
  buildPhase: headers
  type: folder
```

Otherwise I've created PR #245 that may fix your issue. Are you able to test that out, by checking out the branch and running:
```
swift run xcodegen --spec PATH_TO_YOUR_SPEC
```
