### ISSUE TITLE
Carthage Static Dependencies Support

### ISSUE THREAD

**Issue by peymankh** [yonaskolb/XcodeGen#343]
Hi @yonaskolb 

Quick question about Carthage's new static framework support. To my understanding, Carthage will create a separate directory under `build/{Platform}` called `Static`. Do we need to do anything extra to get support for this in Xcodegen.

From the top of my mind, the dependency resolver and framework search paths probably need to be updated?

Thanks.

**Comment by yonaskolb** [comment]
Hi @peymankh 
From looking at Carthage's documentation it seems what we need to do is to add a `static` property to `Dependency` for carthage dependencies that would control: 
- which directory we look for the framework in. Static would look in `Carthage/Build/$(PLATFORM_NAME)/Static`
- whether to add the framework to the Carthage `copy-frameworks` input and output files

**Comment by brentleyjones** [comment]
@yonaskolb That property (or something similar) would be useful for the other forms of `Dependency` as well. Only mentioning it so we name it properly from the start (I’m hoping to tackle the non-Carthage versions of it soon). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yonaskolb** [comment]
@brentleyjones yep, my thinking too 👍

**Comment by brentleyjones** [comment]
@yonaskolb Think I can take a stab at this first? I want to make sure it fits the grander static library/framework vision I'm trying to roll out. If not, that's cool, but one change I was thinking was instead of `static` we call the property `preferredLinkage` (similar to the [buck property](https://buckbuild.com/rule/prebuilt_apple_framework.html#preferred_linkage)) and it defaults to `dynamic` and can be also be set to `static` or `none`. I plan on using the same property and values for other dependency types as well as for `framework` targets.

**Comment by yonaskolb** [comment]
Sounds good. Go for it 👍

**Comment by peymankh** [comment]
@yonaskolb @brentleyjones 

Hey guys,

Thanks for giving this a head start. Just a few notes on adding a new attribute to dependency. To my understanding, we are currently separating out dependencies via their type already i.e. `target` and `carthage`. in regards to other types of dependencies, that probably needs to be defined there not as a new attribute of dependency itself. As for Static carthage dependencies, I'm still not totally convinced, whether a new attribute is necessary. Although I haven't looked at the implementation, would it be possible to pick the framework internally and not mark it explicitly as static or dynamic? So basically if dynamic is available we choose that, if not, we'll try to choose from the Static directory and internally mark it as static to avoid embedding that in the copy frameworks phase. As a result we won't need to add a new attribute to dependency. Optionally we can provide `preferredLinkage` to make this explicit.

On a separate note, have you guys thought about setting `FRAMEWORK_SEARCH_PATHS` to include static frameworks? One thing we can do is to use the current one to search recursively `${CARTHAGE_BUILD_PATH}/${PLATFORM}/**` or add `${CARTHAGE_BUILD_PATH}/Static` if there are any static dependencies available?

What do you think?

**Comment by brentleyjones** [comment]
I'll need to see how it's been implemented. Before this change you could still do static frameworks if they were distributed as binaries. We couldn't tell if they were static or not, so `preferredLinkage` would be required. If Carthage handles it correctly for every case then it won't be needed. Like I mentioned above, you might list a `framework` dependency which is just a path, and we won't know if it's static or dynamic their either, so `preferredLinkage` will be needed for that case as well. A new attribute won't be an issue for Carthage since if we can determine if it's static we would default `preferredLinkage` to the correct thing.

**Comment by peymankh** [comment]
@brentleyjones 

Fair enough. This is how I'm currently using it, which is not the prettiest.

``` yaml
- carthage: Static/Alamofire
  embed: false
```

**Comment by brentleyjones** [comment]
Same. And that currently breaks transitive linking support.

**Comment by peymankh** [comment]
@brentleyjones Definitely, anything I can help to move this forward faster?

**Comment by yonaskolb** [comment]
I'm planning on a release tomorrow. If one of you wants to get this in before then, be my guest!

**Comment by brentleyjones** [comment]
I've started work on this, but it won't make this release.

@peymankh Thanks for the offer. I was just bogged down with other stuff. This is my priority (outside of work) now.

**Comment by brentleyjones** [comment]
No. I made good progress and it’s nearly done, but I’ve gotten side tracked a while ago and I currently don’t have the time to finish it.

I do recommend that we do a simple solution though that simply includes the additional path in the search path. We don’t properly support static frameworks right now (instead doing the “embed: false” hack) and I think the first and easy step would be the continue the status quo here (also require “embed: false” on these). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yonaskolb** [comment]
@brentleyjones would you like to commit what you have to a PR and we can finish it

**Comment by brentleyjones** [comment]
@yonaskolb Not really, sorry. It's a large overhaul of how dependencies are picked up and how static frameworks are seen. It was also before the migration to xcproj 6.
