### ISSUE TITLE
the created project can not be opened by Xcode 10.1(10B61)

### ISSUE THREAD

**Issue by chenyunguiMilook** [yonaskolb/XcodeGen#428]
the created project can not be opened by Xcode 10.1(10B61)

**Comment by yonaskolb** [comment]
Hi @chenyunguiMilook. Can you provide more details? Are you getting some sort of error?

**Comment by chenyunguiMilook** [comment]
It's easy to replicate. 
1. create project.yml (I copy the project config from ReadMe)
2. create two folder MyFramework and MyApp
3. call xcodegen
then open the project, it just can not be opend. I am using the latest xcodegen

**Comment by yonaskolb** [comment]
By latest do you mean 1.11.2 or master? So you have 0 source files? I’ll have to have a look

**Comment by chenyunguiMilook** [comment]
yes, I use brew to install it.

**Comment by yonaskolb** [comment]
Ok, I've found the issue and that is that the Readme example was incorrect! If specifying settings for specific configs, they must go in a `configs` dictionary. Without this it was generated dictionary values for settings which Xcode didn't like.

This is now fixed and some validation added so that xcodegen shows an error in this case https://github.com/yonaskolb/XcodeGen/pull/431
