### ISSUE TITLE
Why static library can not link framework ?

### ISSUE THREAD

**Issue by twoCame** [yonaskolb/XcodeGen#451]
I tried to add dependency to a static library target in a way of framework and carthage, but failed.
And I found the code in PBXProjGenerator.swift, this means a static library can not link frameworks ?

`case .framework:
           guard target.type != .staticLibrary else { break }`
`case .carthage:
           guard target.type != .staticLibrary else { break }`

**Comment by yonaskolb** [comment]
@brentleyjones

**Comment by brentleyjones** [comment]
You link your static libraries dependencies into whatever executable you link your static library to. Static libraries are just archives of code, they don't know how to dynamically link to frameworks. If you try to do this manually in Xcode you even get a warning telling you to not try to link to them since it does nothing.

**Comment by twoCame** [comment]
@brentleyjones 
Thanks for your reply. 
In my case, the code in my static library uses functions and macros from a framework. How to handle this situation?

**Comment by brentleyjones** [comment]
I see there is a slight bug there. It should still include the frameworks in `FRAMEWORK_SEARCH_PATHS` so your code compiles. I'll submit a PR soon.
