### ISSUE TITLE
Parsing existing Xcode project

### ISSUE THREAD

**Issue by drkibitz** [yonaskolb/XcodeGen#568]
This might be a moot request for a project devoted to project generation, though I'll ask the question anyway.

Is there a way to go in reverse, and parse an existing Xcode project to a spec file? Or something at least close to it? Any recommendations? If manual labor is the only answer, would you happen to have any resources to share?

**Comment by yonaskolb** [comment]
Hi @drkibitz. That issue is tracked in #9, so I'll close this one.
At this point crafting the spec by hand is the only way. A few people have been asking for this recently so I’ll see if I can implement a basic version of this soon. PRs welcome.
Migrating all the possible mixed sources is tricky, but we can at least generate all the targets, configurations, and build setting as a starting point
