### ISSUE TITLE
'Shared' scheme option

### ISSUE THREAD

**Issue by ImLaufderZeit** [yonaskolb/XcodeGen#57]
Currently, if you have more than one configs `xcodegen` would make schemes `Shared`.
If there is an option to make a scheme `Shared` checked on, it would be great.

**Comment by yonaskolb** [comment]
Not sure what you mean here @ImLaufderZeit?
The only way to generate shared schemes is by specifying a target `scheme`, or the as yet undocumented top level `schemes`. 
Are you wanting that these generated schemes be optionally made private?

The rest of the private schemes are generated by xcode when you open the project for every target. In Xcode 9 they changed it slightly in that the automatic private schemes aren't written to disk unless you edit them.

**Comment by ImLaufderZeit** [comment]
@yonaskolb, sorry not mentioning any envs or details.
First of all, I'm on Xcode 9 GM and XcodeGen 0.6.1 via `brew`.

Well, under Xcode 8.3.3 & XcodeGen 0.6.1, `xcodebuild -list` did show schemes even if it's not checked as shared. But with Xcode 9 GM & XcodeGen 0.6.1, the command would no longer list schemes unless you manually check `Shared` on.

So, I was bypassing this by adding spec below:

```
    scheme:
      configVariants:
        null
```

... until #50 comes.

**Comment by yonaskolb** [comment]
Ahh I see, you want to simply create a shared scheme right? But you don't want to create config variants as you are just using the default configs, and you have no test targets. That's an interesting point. To fix it, it comes down to how how to specify an empty map in yaml, so it still parses correctly. You can do that with `{}`
```
scheme: {}
```

To make this easier to control, maybe a some sort of `shareScheme` option would be good as you say.

By the way to specify an empty array like you were trying to do with configVariants just use [] (even though you shouldn't need to do that specifically due to the solution above
```
configVariants: []
```
Remember that json is a subset of yaml, so any json format is perfectly fine in a yaml file.

**Comment by ImLaufderZeit** [comment]
> Ahh I see, you want to simply create a shared scheme right? But you don't want to create config variants as you are just using the default configs, and you have no test targets.

Riiight, yes, yes! That's exactly what I wanted to describe. Only default configs, no test targets and single target and scheme.

```
scheme: {}
```

This worked charmingly!! Well, I think I need to learn more how json and yaml works.
Thanks for this 👍

**Comment by ImLaufderZeit** [comment]
Oops, though I closed this issue, I'm totally agreed with:

> To make this easier to control, maybe a some sort of shareScheme option would be good as you say.

But `scheme: {}` works, so later and later. There are issues that has higher priority I guess.

**Comment by ImLaufderZeit** [comment]
Oops, though I closed this issue, I'm totally agreed with:

> To make this easier to control, maybe a some sort of shareScheme option would be good as you say.

But `scheme: {}` works, so later and later. There are issues that has higher priority I guess.

**Comment by yonaskolb** [comment]
Closing as custom schemes can be be generated.
Moving discussion here https://github.com/yonaskolb/XcodeGen/issues/215
