### ISSUE TITLE
Generate project with sub-projects

### ISSUE THREAD

**Issue by carterbitrix** [yonaskolb/XcodeGen#570]
Is there way to generate project with sub-projects?

My frameworks builds in separate projects and I want to use them as dependencies in project which is generated by **xcodegen**

**Comment by dpfannenstiel** [comment]
Could you be a bit more descriptive?  I'm successfully using xcodegen to build multiple projects that have responsibility to build multiple frameworks, executables, and test targets.  All wrapped within a workspace.

**Comment by brennanMKE** [comment]
I am interested in this as well. The way Xcode does source dependencies is to have an Xcode project referenced in another Xcode project. I do not see support to do this with XcodeGen, unless I am just not finding it. I would need to also add a target from the sub-project as a Target Dependency so it builds before the project referencing it. This would put the build product in the same BUILT_PRODUCTS_DIR so that when it is needed it is there.

So far the examples I see are pre-built framework references like is done with Carthage.

**Comment by brennanMKE** [comment]
Btw, if this functionality is not built into XcodeGen, I'd be happy to work on it. I may need some pointers along the way. What I would do is generate a project and a sub-project with a separate `project.yml` and commit them to a local git repo. Then manually add the sub-project so that I can see the difference and work how how to do it with XcodeGen.

**Comment by toshi0383** [comment]
Looks similar to this issue.
https://github.com/yonaskolb/XcodeGen/issues/224

**Comment by yonaskolb** [comment]
Does the solution in #224 work? Create a workspace and use `implicit`? Is it required that there are specifically sub projects as opposed to sibling projects in a workspace?

**Comment by brennanMKE** [comment]
That won't work for me unfortunately due to how we have dependencies and transitive dependencies. It will work for the direct dependencies, but will not work for more complex package configurations. I've been given the green light to work on this update alongside my regular sprint tasks, so I will be figuring this out. I'll use the sample project below as a reference for how to add a group and project reference.

Ideally the changes to project.yml would be simple and logical. I'd like to place all dependencies into a group and then add the project references to that group and then the target dependencies. It may also be necessary to handle embedding, linking as well as copying headers depending on how the dependency is packaged. It may be a dynamic framework or a static library. My preference would be to handle it the same way Swift PM does it which I believe is static. Before I get that far I will need to prototype some options and collect commits that I can reference.

https://github.com/brennanMKE/AtomicXcodeGenSample
