### ISSUE TITLE
`include` feature: Why not xcconfig's `#include` and Xcode's $(inherited) ?

### ISSUE THREAD

**Issue by toshi0383** [yonaskolb/XcodeGen#61]
This is just a question about `include` feature.
How is it different from simply using xcconfig's `#include` and Xcode's `$(inherited)` ?

**Comment by yonaskolb** [comment]
It's similar to xcconfigs `#include` in the way that it merges files. But instead of just using it for build settings you can split up your whole project spec. For example having one yaml file that has common build settings for different projects, or one that has a few targets, that another one then adds to or overrides specific properties of the targets, for example changing the platform of them all or something.
You can see an example here in the tests https://github.com/yonaskolb/XcodeGen/blob/master/Fixtures/include_test.yml
https://github.com/yonaskolb/XcodeGen/blob/master/Fixtures/included.yml

We use it for white label apps, where some things are defined in a `base.yml` and then the different projects have their own `project.yml` that include `base.yml` to override some settings, and add some project specific targets.

In terms of the name, do you suggest something other than `include` to make the purpose clearer? In either case the documentation for this feature should be improved. At the moment it's just documented briefly as a property in the project spec

**Comment by toshi0383** [comment]
Thanks for sharing the details. I think `include` just fits the use-case.👌
It isn't possible to inherit while overriding (like `$(inherited)` of Xcode) though, is it?

**Comment by yonaskolb** [comment]
`$(inherited)` isn't really part of it, as that is inheriting between different levels of settings (target, target config, project, project config, sdk).
Any property that supports `$(inherited)` can actually be an array of values. If you define a setting as an array, then a different spec can add values to this.

This is because the logic of the include merging is as follows:
- if existing value and new value are both dictionaries merge them
- if existing value and new value are both an array then add the value
- otherwise replace the existing value with the new value

This lets you add or replace something deep down in a hierachy. The only downside is that it's not possible to replace a whole dictionary or array as it's additive. I've been thinking of having some sort of syntax for replacing though (something like `targets(REPLACE):`)

Not sure if that all makes sense :)

**Comment by toshi0383** [comment]
Understood. It sounds great!

Because xcconfig's `#include` does not allow inheritance or merging, when you have xcconfig from CocoaPods, configuring your xcconfig is kind of troublesome. [Resently I presented about this](https://speakerdeck.com/toshi0383/xcconfig-pitfalls). So for some users, it can be better option to use XcodeGen's include feature than xcconfig.
Only thing to consider is that XcodeGen is a third party, so it might be broken by future release of Xcode. But it's not likely to happen because pbxproj format haven't changed much for years, did it?
Even `#include` is a bit troublesome as described in my slide, xcconfig is still a good option, too. Because it's even separated from XcodeGen's spec(project.yml), it's easier to be reviewed by or share with others who don't know about XcodeGen.

So I think I'll keep implementing xcconfig feature. 😉

Related: https://github.com/yonaskolb/XcodeGen/issues/59

**Comment by yonaskolb** [comment]
The `:REPLACE` syntax for includes has been added in #68
