### ISSUE TITLE
project status check best practice?

### ISSUE THREAD

**Issue by toshi0383** [yonaskolb/XcodeGen#760]
I imagine a lot of XcodeGen users gitignore `*.xcodeproj`. That is great, but I recognized that I cannot detect if the project is dirty or not, using `git status` or anything.
If something is dirty, CI result might be different from local environment. It's not safe, right?

To resolve this, I personally use status check script to see if target source files are changed since project is generated.
I added [`dump-build-files` command](
https://github.com/toshi0383/hackscode#dump-build-files) to my own tool, and overall workflow is like this.

Generation

```bash
xcodegen
pod install

# Since `pod install` modifies `pbxproj` we cannot directly compare them, so parsing for my interest, in this case, target source files.
hackscode dump-build-files > original-build-files
```

Status Check
```bash
git status
hackscode dump-build-files > current-build-files
if ! diff original-build-files current-build-files > /dev/null
then
    echo ⚠️ pbxproj is modified after generated
    exit 1
fi
```

Let me know if there is better way to workaround the situation.

**Comment by toshi0383** [comment]
By the way my motivation to modify xcodeproj is this.

> Swift compile time is so expensive. Let's ignore all files but one which I'm working on right now.💡

https://github.com/toshi0383/hackscode#remove-build-files

**Comment by Cretus-iosDev** [comment]
I think this should work -

1. Use a Separate Git Repository for Project Files:
One approach is to keep your project files (.xcodeproj and other generated files) in a separate Git repository. This way, you can track changes to the project files independently of your source code repository. This can help ensure that your CI environment is consistent with your local environment.

2. Use a Git Hook:
You can set up a pre-commit Git hook that checks whether the project files have been modified since the last generation. If the project files have changed, the hook can prevent the commit, ensuring that changes to the project files are committed along with changes to the source code. This can help maintain consistency between environments.

3. Scripted Checks:
Your current approach of using a status check script to compare the state of the project files with the source files is valid. However, you can enhance this by scripting it further. For example, you could create a script that checks the Git status, runs XcodeGen if necessary, and then compares the generated project files with the previous state.

**Comment by toshi0383** [comment]
@Cretus-iosDev Thank you for your kind advice!

I don't use XcodeGen in my current project at this time, therefore have no motivation for this issue.
Closing for now.
